### ISSUE TITLE
[メール・共通] メール送信でエラーとなったメールアドレスをログに出力するようにしたい

### ISSUE THREAD

**Issue by masaton0216** [opensource-workshop/connect-cms-ideas#164]
# 背景
 - クライアントから掲示板プラグインからの一斉メール送信時にエラーとの問い合わせあり
 - クライアントのメール環境はwebサーバ（某社クラウドサーバ）とSMTPサーバ（先方ドメイン）が別
 - アプリログに添付のエラーあり
 - おそらく存在しないメールアドレスが混在しており、先方SMTPから554のレスポンスが返ってきたものと想定
# エラー内容
```
[2023-12-04 13:59:08] production.ERROR: Queue::failing ID: Connection:sync Message:Expected response code 354 but got code "554", with message "554 5.5.1 Error: no valid recipients^M
"
[2023-12-04 13:59:08] production.ERROR: Expected response code 354 but got code "554", with message "554 5.5.1 Error: no valid recipients^M
" {"userId":6,"exception":"[object] (Swift_TransportException(code: 554): Expected response code 354 but got code \"554\", with message \"554 5.5.1 Error: no valid recipients

\" at /srv/public_html/www.xxxxx.jp-connect/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:459)
[stacktrace]
#0 /srv/public_html/www.xxxxx.jp-connect/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(344): Swift_Transport_AbstractSmtpTransport->assertResponseCode('554 5.5.1 Error...', Array)
#1 /srv/public_html/www.xxxxx.jp-connect/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php(305): Swift_Transport_AbstractSmtpTransport->executeCommand('DATA\\r\\n', Array, Array, false, NULL)
#2 /srv/public_html/www.xxxxx.jp-connect/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(392): Swift_Transport_EsmtpTransport->executeCommand('DATA\\r\\n', Array, Array)
#3 /srv/public_html/www.xxxxx.jp-connect/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(499): Swift_Transport_AbstractSmtpTransport->doDataCommand(Array)
```

# 対応
 - メール送信でエラーとなったメールアドレスをログに出力するようにしたい。

**Comment by masaton0216** [comment]
よく見たらユーザID：6とあるので、これを元にメールを特定できるかもしれません。
先方に確認して問題クリアできる状況ならば取り下げます。
